spring.application.name=authservice-merezh
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres-authservice:5432/authservice-merezh
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

service.users.url=http://userservice-merezh:8080/api/v1/users

jwt.secret=yXLvsG1Qq8ZkzAiO5xDQY4oR8TqmF0DgswZjSnORre4=
jwt.token.expiration.access=1800
jwt.token.expiration.refresh=604800